on: [workflow_dispatch]

name: Hello js workflow

jobs:
  
  # unit tests
  unit:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: javascript-action
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm test
    - name: nodejsscan scan
      id: njsscan
      uses: ajinabraham/njsscan-action@master
      with:
        args: '.'

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: javascript-action
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm run build --if-present
    # To use this repository's private action,
      # you must check out the repository
    - name: Hello world action step
      uses: ./ # Uses an action in the directory
      id: hello
      with:
        who-to-greet: 'Pepe'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"